/// biome sprite lists

BLOCK_SPRITE_SUMMIT_FULL=ds_list_create()
BLOCK_SPRITE_TEMPLE_FULL=ds_list_create()
BLOCK_SPRITE_SAND_FULL=ds_list_create()
BLOCK_SPRITE_FOREST_FULL=ds_list_create()
BLOCK_SPRITE_CAVE_FULL=ds_list_create()
BLOCK_SPRITE_GUNNY_FULL=ds_list_create()

ds_list_add(BLOCK_SPRITE_SUMMIT_FULL,undefined,grassy1,grassy2,grassy3,grassy4,grassy5,grassy6,grassy7,grassy8,grassy9,grassy10,grassy11,grassy12,grassy13,grassy14,grassy15,grassy16)
ds_list_add(BLOCK_SPRITE_SUMMIT_FULL,grassy5_2,grassy_die_hit,grassy_die_pushed,grassy_die_disintegrated,grassy_die_debris,grassy_die_debris_die)
ds_list_add(BLOCK_SPRITE_TEMPLE_FULL,undefined,newtemple1,newtemple2,newtemple3,newtemple4,newtemple5,newtemple6,newtemple7,newtemple8,newtemple9,newtemple10,newtemple11,newtemple12,newtemple13,newtemple14,newtemple15,newtemple16)
ds_list_add(BLOCK_SPRITE_TEMPLE_FULL,newtemple5_2,newtemple_die_hit,newtemple_die_pushed,newtemple_die_disintegrated,newtemple_die_debris,newtemple_die_debris_die)
ds_list_add(BLOCK_SPRITE_SAND_FULL,undefined,sand1,sand2,sand3,sand4,sand5,sand6,sand7,sand8,sand9,sand10,sand11,sand12,sand13,sand14,sand15,sand16)
ds_list_add(BLOCK_SPRITE_SAND_FULL,sand5_2,sand_die_hit,sand_die_pushed,sand_die_disintegrated,sand_die_debris,sand_die_debris_die)
ds_list_add(BLOCK_SPRITE_FOREST_FULL,undefined,forest1,forest2,forest3,forest4,forest5,forest6,forest7,forest8,forest9,forest10,forest11,forest12,forest13,forest14,forest15,forest16)
ds_list_add(BLOCK_SPRITE_FOREST_FULL,forest5_2,forest_die_hit,forest_die_pushed,forest_die_disintegrated,forest_die_debris,forest_die_debris_die)
ds_list_add(BLOCK_SPRITE_CAVE_FULL,undefined,cave1,cave2,cave3,cave4,cave5,cave6,cave7,cave8,cave9,cave10,cave11,cave12,cave13,cave14,cave15,cave16)
ds_list_add(BLOCK_SPRITE_CAVE_FULL,cave5_2,cave_die_hit,cave_die_pushed,cave_die_disintegrated,cave_die_debris,cave_die_debris_die)
ds_list_add(BLOCK_SPRITE_GUNNY_FULL,undefined,gunny1,gunny2,gunny3,gunny4,gunny5,gunny6,gunny7,gunny8,gunny9,gunny10,gunny11,gunny12,gunny13,gunny14,gunny15,gunny16)
ds_list_add(BLOCK_SPRITE_GUNNY_FULL,gunny5)

